### ISSUE TITLE
Use pandas.Period instead of pandas.Timestamp

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#139] opened 2016-06-15 20:58 UTC
> Since pandas represents timestamps in nanosecond resolution, the timespan that can be represented using a 64-bit integer is limited to approximately 584 years:

>```
In [54]: pd.Timestamp.min
Out[54]: Timestamp('1677-09-22 00:12:43.145225')
In [55]: pd.Timestamp.max
Out[55]: Timestamp('2262-04-11 23:47:16.854775807')
>```

Pandas documentation recommends using `pandas.Period` instead. I think this makes sense for pywr anyway as the dates really represent a period of whatever size the timestep.

**Comment by snorfalorpagus** [comment] 2016-06-16 13:06
Duplicate of #69? I agree we should be using `Period` instead of `Timestamp`.

**Comment by jetuk** [comment] 2016-06-16 21:24
The other issue is the `Period` must have a `freq` i.e. it represents a period of time. So you can have two periods with the same date but different frequencies.

**Comment by snorfalorpagus** [comment] 2016-06-17 07:19
Backtracking on this. We're going to stick with `Timestamp` and avoid massive dates. If you need to work with long stochastic timeseries they should be broken into smaller chunks - they generally don't represent a continuous record anyway.

**Closed by snorfalorpagus** 2016-06-17 07:19 UTC
